
[[pages]]
path = "page/statistics.py"
name = "Issue-Bot í†µê³„ ëŒ€ì‹œë³´ë“œ"
icon = "ğŸ“Š"

[[pages]]
path = "page/view_response.py"
name = "ì±—ë´‡ ì‘ë‹µ ì´ë ¥ í˜ì´ì§€"
icon = "ğŸ“"

[[pages]]
path = "page/analysis.py"
name = "ë¶„ì„ í˜ì´ì§€"
icon = "ğŸ”"
